name = "OpenRouterCLIProxyAPI"
uuid = "d0aa8731-5480-4640-9779-77688f8e2236"
authors = ["SixZero <havliktomi@hotmail.com> and contributors"]
version = "0.1.0"

[deps]
OpenRouter = "b1229eab-bc7b-489c-92b5-04baf87d8d0b"

[compat]
OpenRouter = "1.0"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
